### ISSUE TITLE
Screen resolution

### ISSUE THREAD

**Issue by fritzb** [JeffreyHyer/auto-coc#13]
What is your screen resolution ?
We could change bluestack resolution by running regedt32 with below reg file (for 1024x600), so we don't have to readjust the screen capture you had:

Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\BlueStacks\Guests\Android\FrameBuffer\0]
"Width"=dword:00000400
"Height"=dword:00000258
"WindowWidth"=dword:00000400
"WindowHeight"=dword:00000258
"GuestWidth"=dword:00000400
"GuestHeight"=dword:00000258
"Depth"=dword:00000010
"FullScreen"=dword:00000000
"WindowState"=dword:00000001
"HideBootProgress"=dword:00000001

**Comment by JeffreyHyer** [comment]
My screen resolution is 1920x1080 but BlueStacks runs at 1446x929. I haven't adjusted the resolution of BlueStacks so that's what it runs at by default on my machine.

The issue is that BlueStacks seems to render the graphics differently based on resolution and available video/system memory so even if the resolution is the same if you have a better graphics card than me then BlueStacks will render the graphics better and you'll still need to redo the screen captured images :/
